musicshop/urls.py
from django.conf.urls import url
from . import views
app_name = 'musicshop'

urlpatterns = [
    url(r'^$', views.login, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^articulos/$', views.listararticulos, name='listararticulos'),
    url(r'^crearpedido/$', views.crearpedido, name='crearpedido'),
]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^products', include('musicshop.urls')),
    url(r'^admin/', admin.site.urls),
]

# Crear un PATRON url para los archivos en modo debug
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

musicshop/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class User(AbstractUser):
    is_seller = models.BooleanField(default=False)
    is_client = models.BooleanField(default=True)
    email = models.EmailField(unique=True)
    avatar = models.ImageField(upload_to='users/', null=True, blank=True)

    class Meta:
        db_table = 'auth_user'

    def get_seller_profile(self):
        seller_profile = None
        if hasattr(self, 'sellerprofile'):
            seller_profile = self.sellerprofile
        return seller_profile

    def get_client_profile(self):
        client_profile = None
        if hasattr(self, 'clientprofile'):
            client_profile = self.clientprofile
        return client_profile

    def save(self, *args, **kwargs):
        super(User, self).save(*args, **kwargs)

        if self.is_seller:
            if len(SellerProfile.objects.filter(user=self)) == 0:
                SellerProfile.objects.create(user=self)
        else:
            if len(SellerProfile.objects.filter(user=self)) != 0:
                SellerProfile.delete(SellerProfile.objects.get(user=self))

        if self.is_client:
            if len(ClientProfile.objects.filter(user=self)) == 0:
                ClientProfile.objects.create(user=self)
        else:
            if len(ClientProfile.objects.filter(user=self)) != 0:
                ClientProfile.delete(ClientProfile.objects.get(user=self))

    def __str__(self):
        return '{} {} - {}'.format(self.first_name, self.last_name, self.username)


class SellerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='sellerprofile')

    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)


class ClientProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='clientprofile')

    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)


class TypeArticle(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Article(models.Model):
    GENRE = (
        ('Clasic_Miusic', 'Clasic Miusic'),
        ('Blues', 'Blues'),
        ('Jazz', 'Jazz'),
        ('Rock_and_Roll', 'Rock and Roll'),
        ('Gospel', 'Gospel'),
        ('Soul', 'Soul'),
        ('Country', 'Country'),
        ('Disco', 'Disco'),
    )
    # attributes
    genre = models.CharField(max_length=100, choices=GENRE)
    typee = models.ForeignKey(TypeArticle, on_delete=models.SET_NULL, null=True, related_name='typearticle')
    album = models.CharField(max_length=150)
    artist = models.CharField(max_length=150)
    year = models.DateField(auto_now=False)
    value = models.DecimalField(decimal_places=2, max_digits=10)
    image = models.ImageField(upload_to='articles/', null=True, blank=True)

    def __str__(self):
        return '{} - {}'.format(self.artist, self.album)


class Order(models.Model):
    client = models.ForeignKey(ClientProfile, on_delete=models.CASCADE, related_name='orders')
    seller = models.ForeignKey(SellerProfile, on_delete=models.CASCADE, related_name='orders')
    date = models.DateField(auto_now_add=True)
    total = models.DecimalField(decimal_places=3, max_digits=20)

    def save(selfs, *args, **kwargs):
        if not selfs.id:
            selfs.total = 0
        super(Order, selfs).save(*args, **kwargs)

    def __str__(self):
        return '#{} - Order to {}'.format(self.id, self.client.user.first_name)


class OrderDetail(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='orders')
    amount = models.IntegerField()
    value = models.DecimalField(decimal_places=3, max_digits=20)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='orderdetails')

    def save(self, *args, **kwargs):
        if self.id:
            old = OrderDetail.objects.get(pk=self.id)
            self.order.total -= (old.amount * old.value)
        self.order.total += (self.amount * self.value)
        self.order.save()
        super(OrderDetail, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.order.total -= (self.value * self.amount)
        self.order.save()
        super(OrderDetail, self).delete(*args, **kwargs)

    def __str__(self):
        return 'Order #{} - Detail...'.format(self.order.id)

musicshop/models/articules.py
from django.db import models


class Articule(models.Model):
    TYPES_ARTICULES = (
        ('CASSETE', 'CASSETE'),
        ('LP', 'LP'),
        ('LP', 'VHS'),
        ('LP', 'DVD')
    )
    name = models.CharField(max_length=25, null=True)
    type = models.CharField(max_length=25,choices=TYPES_ARTICULES)
    genere = models.CharField(max_length=25)
    album =models.CharField(max_length=25)
    artist = models.CharField(max_length=25)
    year = models.DateTimeField()
    value = models.IntegerField()

    def __str__(self):
        return '{}'.format(self.name)

musicshop/models/order.py
from django.db import models
from .profile import Client, Seller

from .articules import Articule



class Order(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    date_order = models.DateTimeField()
    total = models.IntegerField()

    def __str__(self):
        return '{} {} {}'.format(self.seller,"sells to", self.client)


class OrderDetail(models.Model):
    articule = models.ForeignKey(Articule, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    value = models.IntegerField()

    order= models.ForeignKey(Order, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return '{}{}'.format(self.quantity,self.value)

musicshop/models/profile.py
from django.db import models
from django.contrib.auth.models import User

class Client(User):

    cellphone = models.IntegerField()
    address = models.CharField(max_length=25)

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)


class Seller(User):

    cellphone = models.IntegerField()
    address = models.CharField(max_length=25)

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)

musicshop/forms.py
from django import forms

from musicshop.models import Pedido


class FormularioAddPedido (forms.ModelForm):

    class Meta:
        model=Pedido
        fields= '__all__'

musicshop/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.template import loader

from musicshop.forms import FormularioAddPedido
from musicshop.models import Articulo


def listArt (request):
    template=loader.get_template('listArt.html')
    dato=Articulo.objects.order_by('id')
    contexto={
        'articulo': dato
    }
    return HttpResponse(template.render(
        contexto,request
    ))


def addPedido (request):
    if request.method=='POST':
        formulario=FormularioAddPedido(request.POST)
        if formulario.is_valid():
            articulo=formulario.save()
            articulo.save()
            return HttpResponseRedirect('addPedido')

    else:
        formulario=FormularioAddPedido()
    template= loader.get_template('addPedido.html')
    contexto = {
            'formulario':formulario,
        }
    return HttpResponse(template.render(contexto,request))

musicshop/templates/base/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<html lang="{{ LANGUAGE_CODE }}">

<head>
    <meta charset="UTF-8">
    <title>{% block titulo_ventana %} Titulo de ventana {% endblock %}| Django 1.11</title>

    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'dist/icono.ico' %}" />
    <!-- Bootstrap 3.3.2 -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css " />
    <!-- DATA TABLES -->
    <link href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}" rel="stylesheet" type="text/css" />
    <!-- FontAwesome 4.3.0 -->
    <link href="{% static 'plugins/font-awesome/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{% static 'dist/css/AdminLTE.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link href="{% static 'dist/css/skins/_all-skins.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- bootstrap-select-1.12.4 -->
    <link href="{% static 'plugins/bootstrap-select-1.12.4/css/bootstrap-select.min.css' %}" rel="stylesheet" type="text/css" />
<link href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.2.0/animate.min.css" rel="stylesheet">
    {#    estilos personalizados#}
    <link href="{% static 'dist/css/mystyles.css' %}" rel="stylesheet" type="text/css" />
    <!-- Estilos extra / OPCIONAL -->

    {% block extrastyle %} {% endblock %}

</head>

<body class="skin-blue fixed" >
    <div class="wrapper" id="inner-content-div">

        {% block header %}
        {# barra principal / nav #}
            {% include 'base/header.html' %}
        {% endblock %}

        {% block sidebar %}
             {# Columna del lado izquierdo. contiene el logo y la barra lateral #}
            {% include 'base/sidebar.html' %}
        {% endblock %}

        {# contenido de la pagina #}
        <!-- Right side column. Contains the navbar and content of the page -->

         <div class="content-wrapper">
              <!-- Content Header (Page header) -->
              <section class="content-header">
                  <h1>{% block titulo %}{% endblock %}</h1>
                  <h1><small>{% block subtitulo %} {% endblock %}</small></h1>
              </section>

              <!-- Main content -->
              <section class="content">
                    <div class="row">
                        {% block content %} {% endblock %}
                    </div>
              </section>
          </div><!-- ./content-wrapper -->

          <footer class="main-footer">
               <div class="pull-right hidden-xs">
                    <b>Version</b> 1.0
               </div>
               <strong>Copyright &copy; 2018 <a href="http://oscloud.co" target="_blank">Oscloud Tecnología</a>.</strong> Todos los derechos reservados.
          </footer>
    </div><!-- ./wrapper -->

    <!-- jQuery 2.1.3 -->
    <script src="{% static 'plugins/jQuery/jQuery-2.1.3.min.js' %}"></script>
    <!-- jQuery UI 1.11.2 -->
    <script src="{% static 'plugins/jQueryUI/jquery-ui.min.js' %}" type="text/javascript"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <!-- DATA TABLES SCRIPT -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}" type="text/javascript"></script>
    <!-- Slimscroll -->
    <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}" type="text/javascript"></script>
    <!-- FastClick -->
    <script src="{% static 'plugins/fastclick/fastclick.min.js' %}"></script>
    <!-- bootstrap-select-1.12.4 -->
    <script src="{% static 'plugins/bootstrap-select-1.12.4/js/bootstrap-select.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'plugins/bootstrap-select-1.12.4/js/i18n/defaults-es_ES.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'plugins/bootstrap-notify/bootstrap-notify.js' %}" type="text/javascript"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/app.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'dist/js/table_selectMultiple.js' %}" type="text/javascript"></script>
    {#Scripts personalizados#}
    <script src="{% static 'dist/js/myscripts.js' %}" type="text/javascript"></script>
    <script>
        $(function(){
             var viewportHeight= $(window).height();
             $('#inner-content-div').slimScroll({
                  height: viewportHeight+'px',
             });
        });
    </script>
<!-- JS extra / OPCIONAL -->
{% block extrascript %} {% endblock %}
</body>
</html>

musicshop/templates/base/header.html
{% load staticfiles %}
<header class="main-header">
    <!-- Logo -->
    <a class="logo" href=""><b>Project</b> Man</a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="user-footer">
                   <a href="{% url 'projectman:logout' %}" role="button">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

musicshop/templates/base/sidebar.html
{% load staticfiles %}
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="/media/admin.png" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <a role="button"><i class="fa fa-circle text-success"></i> En linea</a>
                <p></p>
                <p role="button" style="margin-left: 2em">{{ request.user }}</p>
            </div>
        </div>
        <ul class="sidebar-menu">
            <li class="header">MENU DE NAVEGACIÓN</li>
            <li><!-- Inicio -->
                <a href="{% url 'projectman:dashboard' %}">
                    <i class="fa fa-home"></i><span>Inicio</span>
                </a>
            </li>
                <li class="header">Proyectos</li>
            {% if request.user.is_project_manager %}
                <li class="treeview"><!-- Proyectos -->
                    <a href="#">
                        <i class="fa fa-briefcase"></i> <span>Proyectos</span> <i class="fa fa-angle-left pull-right"></i>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{% url 'projectman:build_project' %}"><i class="fa fa-file-o"></i> Nuevo Proyecto</a></li>
                        <li><a href="{% url 'projectman:list_project' %}"><i class="fa fa-list"></i> Lista Proyectos</a></li>
                    </ul>
                </li>
            {% endif %}
            {% if request.user.is_client %}
                <li class="treeview"><!-- Proyectos -->
                    <a href="#">
                        <i class="fa fa-briefcase"></i> <span>Mis Proyectos</span> <i class="fa fa-angle-left pull-right"></i>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href="{% url 'projectman:list_project_client' request.user.id %}"><i class="fa fa-list"></i> Lista Proyectos</a></li>
                    </ul>
                </li>
            {% endif %}
            <li class="treeview"><!-- Tareas -->
                <a href="#">
                    <i class="fa fa-list-alt"></i> <span>Tareas</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{% url 'projectman:build_task' %}"><i class="fa fa-file-o"></i> Nueva Tarea</a></li>
                    <li><a href="{% url 'projectman:list_task' %}"><i class="fa fa-list"></i> Lista Tareas</a></li>
                </ul>
            </li>
            <li class="treeview"><!-- Comentarios -->
                <a href="#">
                    <i class="fa fa-comments"></i> <span>Comentarios</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{% url 'projectman:build_comment' %}"><i class="fa fa-file-o"></i> Nuevo Comentario</a></li>
                    <li><a href="{% url 'projectman:list_comment' %}"><i class="fa fa-list"></i> Lista Comentarios</a></li>
                </ul>
            </li>
           {% if request.user.is_project_manager %}
            <li class="header">Usuarios</li>
                <li class="treeview"><!-- Check List -->
                    <a href="#">
                        <i class="fa fa-user"></i>
                        <span>Usuarios</span><i class="fa fa-angle-left pull-right"></i>
                    </a>
                    <ul class="treeview-menu">
                        <li><a href=""><i class="fa fa-circle-o"></i> Nuevo</a></li>
                        <li><a href=""><i class="fa fa-list"></i> Lista</a></li>
                    </ul>
                </li>
            {% endif %}
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

musicshop/templates/crearpedido.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
CREACION DE PEDIDO PARA CLIENTE
<form method="POST">
    {% csrf_token %}
    <label>Fecha del pedido</label><input type="date" name="fecha"/>
    <input type="submit" value="Submit"/>
</form>
</body>
</html>

musicshop/templates/listaarticulos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url "musicshop:crearpedido" %}">Crear pedido</a>
    <table>
        <thead>
                <th>
                    Genero
                </th>
                <th>
                    Tipo de articulo
                </th>
                <th>
                    Album
                </th>
                <th>
                    Artista
                </th>
                <th>
                    Año
                </th>
                <th>
                    Valor
                </th>
        </thead>       <tbody>
{% for articulo in articulos %}


            <tr>
                <td>{{ articulo.genero }}</td>
                <td>{{ articulo.tipoarticulo }}</td>
                <td>{{ articulo.album }}</td>
                <td>{{ articulo.artista }}</td>
                <td>{{ articulo.anio }}</td>
                <td>{{ articulo.valor }}</td>
            </tr>

{% endfor %}
    </tbody>
    </table>
</body>
</html>

musicshop/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Inicio de sesión | MusicShop</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">

{% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    {% endif %}

  {% if form.errors %}
    <p class="error">Sorry, that's not a valid username or password</p>
  {% endif %}

<div class="login-box">
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Inicio de sesión</p>

    <form action="" method="POST">
    {% csrf_token %}
      <div class="form-group has-feedback">
        <input type="text" class="form-control" placeholder="Username" name="username">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="Password" name="password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

    


  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
</body>
</html>

templates/articules/articules.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>Articles</h1>
<ul>
{% for article in object_list %}
    <li>{{ article.name }} - {{ article.type }} - {{ article.genere }} - {{ article.album }} - {{ article.year }} - {{ article.value }} </li>
{% empty %}
    <li>No articles yet.</li>
{% endfor %}
</ul>

</body>
</html>

templates/crear.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block contenido %}
<div class="container">
    <div class="col sm-6">
        <form method="post">
    {% csrf_token %}
    {{  form.as_p }}
    <button type="submit">Guardar</button>
</form>
    </div>
</div>
{% endblock %}

templates/editar.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block contenido %}
<form method="post">
    {% csrf_token %}
    {{  form.as_p }}
    <button type="submit">Editar</button>
</form>
{% endblock %}

templates/inclusion_tags/messages.html
{% if form.non_field_errors %}
    <div class="col-md-12">
        <div class="alert alert-warning alert-dismissable alert-margin">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4><i class="fa fa-warning"></i> Error!</h4>
            {{ form.non_field_errors }}
        </div>
    </div>
{% endif %}

{% if messages %}
    {% for message in messages %}
        {% ifequal message.tags 'success' %}
            <div class="alert alert-success alert-dismissible alert-margin">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="fa fa-check"></i> Muy bien!</h4>
                <span>{{ message }}!</span>
            </div>
        {% else %}
            <div class="alert alert-error alert-dismissible alert-margin">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h4><i class="fa fa-ban"></i> Error!</h4>
                <span>{{ message }}!</span>
            </div>
        {% endifequal %}
    {% endfor %}
{% endif %}

templates/inclusion_tags/modal_eliminar.html
<!-- Modal -->
<div class="modal fade modal-danger" id="modal-eliminar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Eliminar</h4>
            </div>
            <div class="modal-body">
                <h4>¿Está seguro que desea eliminar <span id="span-ms"></span>?</h4>
                <h4 id="body-ms"></h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Cancelar</button>
                <form method="post" id="form-eliminar">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline pull-right">Eliminar</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/invoice/invoice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


<form action="{% url 'musicshop:create_order' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Registrar</button>




</form>
</body>
</html>

templates/musicshop/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MS - Dashboard</title>
</head>
<body>

<h1> Bienvenido {{ request.user }}</h1>

{% if request.user.user_type == 'Seller' %}
    <ul>
        <li><a href="{% url 'musicshop:create_order' %}">Registrar Pedido.</a></li>
        <li><a href="{% url 'musicshop:create_tarticle' %}">Crear Tipo Articulo.</a></li>
        <li><a href="{% url 'musicshop:create_article' %}">Crear Articulo.</a></li>
        <li><a href="{% url 'musicshop:view_orders' %}">Ver pedidos.</a></li>
        <li><a href="{% url 'musicshop:view_article' %}">Ver Articulos.</a></li>
    </ul>
{% else %}
    <ul>
        <li><a href="{% url 'musicshop:view_orders' %}">Ver pedidos.</a></li>
        <li><a href="{% url 'musicshop:view_article' %}">Ver Articulos.</a></li>
    </ul>
{% endif %}


<hr>
<a href="{% url 'musicshop:logout' %}">Logout</a>

</body>
</html>

templates/musicshop/detallepedido_delete .html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/musicshop/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MS - Logout</title>
</head>
<body>
<a href="{% url 'musicshop:index' %}">Regresar</a>
</body>
</html>